services:
  backend:
    image: docker.io/tobiashochguertel/th-helm-playground-backend:latest
    volumes:
      - /Users/tobiashochgurtel/work-dev/quiz/helm-chart/quiz:/app/public
    environment:
      - PORT=3001
    restart: always
  template:
    image: docker.io/tobiashochguertel/th-helm-playground-template:latest
    environment:
      - PORT=3002
    restart: always
  frontend:
    image: docker.io/tobiashochguertel/th-helm-playground-frontend:latest
    ports:
      - 4173:80
    environment:
      - BACKEND_PORT=3001
      - BACKEND_HOSTNAME=backend
      - BACKEND_TEMPLATE_PORT=3002
      - BACKEND_TEMPLATE_HOSTNAME=template
    restart: always
