#!/bin/bash

COMPOSE_FILE="$HOME/bin/edit-chart.docker-compose.yml"
CURRENT_PATH="$(pwd)"

"$HOME"/bin/edit-chart.dasel put -f "$COMPOSE_FILE" -s 'services.backend.volumes.index(0)' -v "$CURRENT_PATH:/app/public"
# cat "$COMPOSE_FILE"
docker-compose -f "$COMPOSE_FILE" down
docker-compose -f "$COMPOSE_FILE" up  --remove-orphans --pull always -d

sleep 1

echo ""
echo "open http://localhost:4173"
echo ""

if [[ $OSTYPE == 'darwin'* ]]; then
  open http://localhost:4173
fi